# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [9]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [10]:
np.__version__

'2.3.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [11]:
Z=np.zeros(10)
Z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [12]:
print("size in byptes:- ",Z.nbytes)

size in byptes:-  80


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [13]:
python -c "import numpy; help(numpy.add)"

SyntaxError: invalid syntax (442374612.py, line 1)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [18]:
Z=np.zeros(10)
Z[4]=1
Z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [22]:
vec=np.arange(10,50)
vec

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [27]:
vec[::-1]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [28]:
matrix=np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [31]:
arr=np.array([1,2,0,0,4,0])
indices=np.nonzero(arr)[0]
indices

array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [33]:
i_matrix=np.identity(3)
i_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [41]:
ran_val_mat=np.random.random((3,3,3))
ran_val_mat

array([[[0.6285265 , 0.18562507, 0.05213065],
        [0.94297611, 0.91754102, 0.88463736],
        [0.57927413, 0.16551142, 0.04019671]],

       [[0.70568446, 0.72924944, 0.50106306],
        [0.61944738, 0.34829914, 0.08623995],
        [0.09771711, 0.42868166, 0.54754616]],

       [[0.07639224, 0.17638687, 0.62659046],
        [0.42987757, 0.56286337, 0.688468  ],
        [0.33473431, 0.25404619, 0.76488216]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [47]:
min_max=np.random.random((10,10))
min_val=min_max.min()
max_val=min_max.max()
print(min_val,max_val)

0.005717717008386414 0.9813971772472125


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [52]:
ran_vec=np.random.random(30)
mean=np.mean(ran_vec)
mean

np.float64(0.49126234589099393)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [60]:
Z=np.ones([5,5])
Z[1:-1,1:-1]=0
Z


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [14]:
Z_padded=np.pad(Z,pad_width=1,mode='constant',constant_values=0)
Z_padded

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [15]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)

nan
False
False
nan


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [16]:
new_mat=np.diag(np.arange(1,5),k=-1)
new_mat

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [17]:
checkboard=np.ones((8,8),dtype=int)
checkboard[1::2,::2]=0
checkboard[::2,1::2]=0
checkboard

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [18]:
index=np.unravel_index(99,(6,7,8))
print(index)

(np.int64(1), np.int64(5), np.int64(3))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [96]:
pattern = np.array([[0, 1], [1, 0]])
checkerboard = np.tile(pattern, (4,4))
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [103]:
Z=np.random.random((5,5))
Z_norm=(Z-Z.min())/(Z.max()-Z.min())
Z_norm



array([[0.        , 0.9154046 , 0.18779807, 0.49331048, 0.43122342],
       [0.78672538, 0.14034445, 0.04745463, 0.83583939, 0.07350995],
       [0.68376261, 0.38762853, 0.2284803 , 0.10590495, 0.55559001],
       [0.76822707, 0.66165295, 0.63669109, 0.92538973, 0.5388851 ],
       [0.01507275, 0.05271735, 0.36363614, 1.        , 0.79015183]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [111]:
rgba_dtype = np.dtype([('r', np.uint8), ('g', np.uint16), ('b', np.uint32), ('a', np.uint64)])
rgba_dtype

dtype([('r', 'u1'), ('g', '<u2'), ('b', '<u4'), ('a', '<u8')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [21]:
a=np.random.random((5,3))
b=np.random.random((3,2))
pro=np.dot(a,b)
pro

array([[0.23798181, 0.01826603],
       [0.82282978, 0.40554234],
       [0.66832665, 0.13475721],
       [0.85999767, 0.15036266],
       [0.75305708, 0.52955093]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [120]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr[(arr>=3) & (arr<=8)]*=-1
arr

array([ 1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [130]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [132]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\Devarshi\AppData\Local\Temp\ipykernel_3284\478919562.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Devarshi\AppData\Local\Temp\ipykernel_3284\478919562.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Devarshi\AppData\Local\Temp\ipykernel_3284\478919562.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [19]:
x = np.array([-1.7, -0.2, 0.2, 1.7])
rounded = np.copysign(np.ceil(np.abs(x)), x)
print(rounded)

[-2. -1.  1.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [25]:

a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])
common=np.intersect1d(a,b)
common

array([3, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [27]:
np.seterr(all='ignore')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [28]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [32]:
today=np.datetime64('today','D')
yesterday=today-np.timedelta64(1,'D')
tomo=today+np.timedelta64(1,"D")

today,yesterday,tomo

(np.datetime64('2025-09-08'),
 np.datetime64('2025-09-07'),
 np.datetime64('2025-09-09'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [34]:
dates=np.arange('2016-07','2016-08',dtype='datetime64[D]')
dates

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [35]:
A = np.random.random(5)
B = np.random.random(5)

A += B
A *= -A / 2

print(A)

[-0.68282232 -0.4892943  -0.33260502 -0.62615838 -0.63186882]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [38]:
Z = np.random.uniform(0, 10, 10)

int1=Z.astype(int)
int2=np.floor(Z)
int3=np.trunc(Z)
int4=np.fix(Z)

int1,int2,int3,int4

(array([5, 8, 1, 4, 1, 1, 0, 1, 4, 5]),
 array([5., 8., 1., 4., 1., 1., 0., 1., 4., 5.]),
 array([5., 8., 1., 4., 1., 1., 0., 1., 4., 5.]),
 array([5., 8., 1., 4., 1., 1., 0., 1., 4., 5.]))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [44]:
mat=np.tile(np.arange(5),(5,1))
mat

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [45]:
def gen():
    for i in range(10):
        yield i

arr = np.fromiter(gen(), dtype=int)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [48]:
vec=np.linspace(0,1,12,endpoint=False)[1:-1]
vec

array([0.08333333, 0.16666667, 0.25      , 0.33333333, 0.41666667,
       0.5       , 0.58333333, 0.66666667, 0.75      , 0.83333333])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [54]:
vec=np.random.random(10)
vec_sorted=np.sort(vec)
vec_sorted

array([0.00904185, 0.17640451, 0.33663339, 0.34273438, 0.44590272,
       0.46958806, 0.51529604, 0.68997807, 0.85611425, 0.95754008])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [55]:
arr = np.array([1, 2, 3, 4, 5])
result = sum(arr)
print(result)

15


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [57]:
A=np.random.random(10)
B=np.random.random(10)

np.equal(A,B)

array([False, False, False, False, False, False, False, False, False,
       False])

#### 43. Make an array immutable (read-only) (★★☆)

In [58]:
arr=np.arange(10)
arr.flags.writeable=False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [2]:
vec=np.random.random((10,2))

NameError: name 'np' is not defined

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)