In [2]:
import numpy as np
import matplotlib.pyplot as plt


In [3]:
A=np.array([[0.5,0.5,0.25],[0.25,0.0,0.25],[0.25,0.5,0.5]])
print(A)

[[0.5  0.5  0.25]
 [0.25 0.   0.25]
 [0.25 0.5  0.5 ]]


In [4]:
xtoday=np.array([[1],[0],[0]])
print(xtoday)

[[1]
 [0]
 [0]]


In [6]:
print(A@xtoday)

[[0.5 ]
 [0.25]
 [0.25]]


In [20]:
for k in range(1,50):
    xtommorow=A@xtoday
    print(f"<---{k}--->\n", xtommorow)
    xtoday=xtommorow

<---1--->
 [[0.4]
 [0.2]
 [0.4]]
<---2--->
 [[0.4]
 [0.2]
 [0.4]]
<---3--->
 [[0.4]
 [0.2]
 [0.4]]
<---4--->
 [[0.4]
 [0.2]
 [0.4]]
<---5--->
 [[0.4]
 [0.2]
 [0.4]]
<---6--->
 [[0.4]
 [0.2]
 [0.4]]
<---7--->
 [[0.4]
 [0.2]
 [0.4]]
<---8--->
 [[0.4]
 [0.2]
 [0.4]]
<---9--->
 [[0.4]
 [0.2]
 [0.4]]
<---10--->
 [[0.4]
 [0.2]
 [0.4]]
<---11--->
 [[0.4]
 [0.2]
 [0.4]]
<---12--->
 [[0.4]
 [0.2]
 [0.4]]
<---13--->
 [[0.4]
 [0.2]
 [0.4]]
<---14--->
 [[0.4]
 [0.2]
 [0.4]]
<---15--->
 [[0.4]
 [0.2]
 [0.4]]
<---16--->
 [[0.4]
 [0.2]
 [0.4]]
<---17--->
 [[0.4]
 [0.2]
 [0.4]]
<---18--->
 [[0.4]
 [0.2]
 [0.4]]
<---19--->
 [[0.4]
 [0.2]
 [0.4]]
<---20--->
 [[0.4]
 [0.2]
 [0.4]]
<---21--->
 [[0.4]
 [0.2]
 [0.4]]
<---22--->
 [[0.4]
 [0.2]
 [0.4]]
<---23--->
 [[0.4]
 [0.2]
 [0.4]]
<---24--->
 [[0.4]
 [0.2]
 [0.4]]
<---25--->
 [[0.4]
 [0.2]
 [0.4]]
<---26--->
 [[0.4]
 [0.2]
 [0.4]]
<---27--->
 [[0.4]
 [0.2]
 [0.4]]
<---28--->
 [[0.4]
 [0.2]
 [0.4]]
<---29--->
 [[0.4]
 [0.2]
 [0.4]]
<---30--->
 [[0.4]
 [0.