In [2]:
import tensorflow as tf
# Scalar
scalar=tf.constant(5)
print(scalar)

# vector
vector = tf.constant([1,2,3,4])
print(vector)

# MAtrix
matrix =tf.constant([[1,2],[3,4]])
print(matrix.shape)

# random tensor
rand_tensor=tf.random.normal([3,3],mean=0.0,stddev=1.0)
print(rand_tensor)

tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
(2, 2)
tf.Tensor(
[[ 0.96422064 -0.06666744 -1.1571382 ]
 [ 0.72706616  1.1699833   1.2744148 ]
 [-0.4795448  -0.59564054 -0.6331872 ]], shape=(3, 3), dtype=float32)


In [3]:
a = tf.constant([1,2,3], dtype=tf.float32)
b = tf.constant([4,5,6], dtype=tf.float32)

# Addition
c = tf.add(a, b)       # [5,7,9]

# Multiplication (element-wise)
d = tf.multiply(a, b)

# Matrix multiplication
mat1 = tf.constant([[1,2],[3,4]])
mat2 = tf.constant([[5,6],[7,8]])
mat_mul = tf.matmul(mat1, mat2)
print(mat_mul)

# Transpose
print(tf.transpose(mat1))


tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


## In deep learning, weights are tensors that we need to update. These are created using tf.Variable

In [10]:
W=tf.Variable([[0.5,1.0],[1.5,-0.5]],dtype=tf.float32)
b=tf.Variable([0.0,0.0],dtype=tf.float32)

x=tf.constant([[1.0,2.0]])
y=tf.matmul(x,W)+b
print(y)

tf.Tensor([[3.5 0. ]], shape=(1, 2), dtype=float32)


Automatic Differentiation

TensorFlow uses tf.GradientTape to compute derivatives automatically.

In [5]:
x=tf.constant([[1.0,2.0]])
with tf.GradientTape() as tape:
    y=tf.matmul(x,W)+b
    loss=tf.reduce_sum(y**2)

grads=tape.gradient(loss,[W,b])
print(grads)

[<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 7.,  0.],
       [14.,  0.]], dtype=float32)>, <tf.Tensor: shape=(2,), dtype=float32, numpy=array([7., 0.], dtype=float32)>]


In [6]:
# TensorFlow 2.x uses Eager Execution by default, which is intuitive and Pythonic.
# Eager Execution: operations are computed immediately.
# Graph Mode (optional): you can convert functions to a static graph using @tf.function for faster execution.


@tf.function
def f(x):
    return x**2+2*x+1
print(f(tf.constant(3.0)))


tf.Tensor(16.0, shape=(), dtype=float32)
