In [ ]:
import numpy as np

R = np.array([
    [5, 3, 0, 1],
    [4, 0, 0, 1],
    [1, 1, 0, 5],
    [1, 0, 0, 4],
    [0, 1, 5, 4],
], dtype=float)

num_users,num_items=R.shape
k=2
P=np.random.rand(num_users,k)
Q=np.random.rand(num_items,k)

learning_rate=0.01
lambda_reg = 0.02
epochs = 5000

for epoch in range(epochs):
    for i in range(num_users):
        for j in range(num_items):
            if(R[i][j])> 0:
                eij=R[i][j]-np.dot(P[i,:],Q[j,:])
                P[i,:]+=learning_rate*(eij*Q[j,:]-lambda_reg*P[i,:])
                Q[j,:]+=learning_rate*(eij*P[i,:]-lambda_reg*Q[j,:])



R_hat = np.dot(P, Q.T)
print(np.round(R_hat, 2))

[[4.95 2.97 1.87 1.  ]
 [3.96 2.39 1.73 1.  ]
 [1.   1.   6.11 4.94]
 [1.   0.91 4.93 3.97]
 [1.14 1.   4.97 3.99]]


| Concept       | Description                            | Common Use                 |
| ------------- | -------------------------------------- | -------------------------- |
| **SVD**       | Orthogonal low-rank decomposition      | PCA, LSA                   |
| **NMF**       | Non-negative low-rank                  | Image parts, topics        |
| **ALS**       | Alternating least squares optimization | Recommenders               |
| **PMF**       | Bayesian MF with priors                | Collaborative filtering    |
| **Neural MF** | Deep nonlinear embeddings              | Netflix, Spotify           |
| **Tensor MF** | Multi-dimensional extension            | Context-aware recommenders |
